memo/app/urls.py
from django.urls import path

from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:memo_id>', views.detail, name='detail'),
    path('new_memo', views.new_memo, name='new_memo'),
    path('delete_memo/<int:memo_id>', views.delete_memo, name = 'delete_memo'),
    path('edit_memo/<int:memo_id>', views.edit_memo, name='edit_memo'),
    ]

memo/memo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('app.urls'))
]

memo/app/models.py
from django.db import models

# Create your models here.
class Memo(models.Model):
    title = models.CharField(verbose_name='タイトル', max_length=150)
    text = models.TextField(blank=True)
    created_datetime = models.DateTimeField(auto_now_add=True)
    update_datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

memo/app/forms.py
from django.forms import ModelForm


from .models import Memo


class MemoForm(ModelForm):
    class Meta:
        model = Memo
        fields = ['title', 'text']

memo/app/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.views.decorators.http import require_POST


from .models import Memo
from .forms import MemoForm
# Create your views here.
def index(request):
    memos = Memo.objects.all().order_by('-update_datetime')
    return render(request, 'app/index.html', {'memos' : memos})

def detail(request, memo_id):
    memo = get_object_or_404(Memo, id = memo_id)
    return render(request, 'app/detail.html', {'memo' : memo})

def new_memo(request):
    if request.method == 'POST':
        form = MemoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('app:index')
    else:
        form = MemoForm
    return render(request, 'app/new_memo.html', {'form' : form})

@require_POST
def delete_memo(request, memo_id):
    memo = get_object_or_404(Memo, id = memo_id)
    memo.delete()
    return redirect('app:index')

def edit_memo(request, memo_id):
    memo = get_object_or_404(Memo, id=memo_id)
    if request.method == "POST":
        form = MemoForm(request.POST, instance=memo)
        if form.is_valid():
            form.save()
            return redirect('app:index')
    else:
        form = MemoForm(instance=memo)
    return render(request, 'app/edit_memo.html', {'form':form, 'memo':memo})

memo/app/templates/app/detail.html
<a href="{% url 'app:index' %}">ホームに戻る</a>

<h2>{{ memo.title }}</h2>

{{ memo.text | linebreaks | urlize }}
<button><a href="{% url 'app:edit_memo' memo.pk %}">編集</a></button>
<form action="{% url 'app:delete_memo' memo.pk %}" method="post">
  {% csrf_token %}
  <button type="submit" name="button"
  onclick="return confirm('本当に削除しますか？');">削除</button>
</form>

memo/app/templates/app/edit_memo.html
<a href="{% url 'app:detail' memo.id %}">戻る</a>

<form action="{% url 'app:edit_memo' memo.id %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" name="button">保存</button>
</form>

memo/app/templates/app/index.html
<a href="{% url 'app:new_memo' %}">新規メモ作成</a>

{% for memo in memos %}
<a href="{% url 'app:detail' memo.id %}">
  <br>{{ memo }}
  <span>{{ memo.updated_datetime }}</span>
</a>
{% endfor %}

memo/app/templates/app/new_memo.html
<a href="{% url 'app:index' %}">ホームに戻る</a>


<form action="{% url 'app:new_memo' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" name="button">保存</button>
</form>